<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Wublish 0.0.1</title>

    <link rel="stylesheet" href="/wublish-assets/css/style.css" />
</head>
<body>
    <div class="container">
        <h1><?php echo isset($title) ? $title : "Hello world!"; ?></h1>

        <?php if ($user): ?>
            <p>Logged in as <?php echo $user['name']; ?> <a href="/logout">Logout</a></p>
        <?php else: ?>
            <p>Not logged in <a href="/login">Login</a></p>
        <?php endif; ?>

        <div class="cols">
            <?php if (isset($pagetree)) echo $pagetree; ?>
        </div>
    </div>
</body>
</html>
