<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Login</title>

    <link rel="stylesheet" href="/wublish-assets/css/style.css" />
</head>
<body>

    <form method="post">
        <h1>Login</h1>
        <?php if (isset($errors['general'])) echo '<div class="error message">' . $errors['general'] . '</div>'; ?>
        <div class="field">
            <label for="login_username">Username</label>
            <input type="text" name="username" id="login_username" value="<?php if (isset($values['username'])) echo $values['username']; ?>" />
            <?php if (isset($errors['username'])) echo '<div class="error">' . $errors['username'] . '</div>'; ?>
        </div>
        <div class="field">
            <label for="login_password">Password</label>
            <input type="password" name="password" id="login_password" value="<?php if (isset($values['password'])) echo $values['password']; ?>" />
            <?php if (isset($errors['password'])) echo '<div class="error">' . $errors['password'] . '</div>'; ?>
        </div>
        <div class="buttons">
            <button type="submit">Login</button>
        </div>
    </form>
</body>
</html>
